# -*- coding: utf-8 -*-
"""ImageCaptioning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h21uEw3agQH4cH6W5a3iPCKn7SDQcnwL
"""

# 1. Install required libraries
!pip install -q transformers pillow torch

import torch
from PIL import Image
from transformers import BlipProcessor, BlipForConditionalGeneration
from google.colab import files

# 2. Setup Device (Uses GPU if available)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# 3. Load the BLIP model (Base version for speed)
processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(device)

def caption_my_image():
    # 4. Upload your image directly to Colab
    print("Please upload an image...")
    uploaded = files.upload()

    for filename in uploaded.keys():
        raw_image = Image.open(filename).convert('RGB')

        # 5. Process and Generate
        inputs = processor(raw_image, return_tensors="pt").to(device)
        out = model.generate(**inputs)

        # 6. Output Result
        caption = processor.decode(out[0], skip_special_tokens=True)
        print("-" * 30)
        print(f"FILE: {filename}")
        print(f"CAPTION: {caption}")
        print("-" * 30)

# Run the function
caption_my_image()